language: bash
os: linux

services:
  - docker

env:
  global:
    - DOCKERHUB="thecaptain989/flac2mp3-mod"

if: (NOT (type IN (pull_request)))

# YAML anchors used elsewhere
_git_version: &git_version
  - VERSION=$(git describe --tags --always)
_docker_login: &docker_login
  - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin

jobs:
  include:
    - stage: BuildImage
      name: build amd64
      arch: amd64
      script:
        # Build variables
        - <<: *git_version
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          --file Dockerfile
          --tag ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:amd64
        # Login to DockerHub
        - <<: *docker_login
        # Push the tag
        - docker push ${DOCKERHUB}:amd64
    - name: build arm64
      arch: arm64
      script:
        # Build variables
        - <<: *git_version
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          --file Dockerfile.arm64
          --tag ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:arm64
        # Login to DockerHub
        - <<: *docker_login
        # Push the tag
        - docker push ${DOCKERHUB}:arm64
    - stage: dockerhub push
      script:
        - docker pull ${DOCKERHUB}:amd64
        - docker pull ${DOCKERHUB}:arm64
        - docker manifest create ${DOCKERHUB}:latest ${DOCKERHUB}:amd64 ${DOCKERHUB}:arm64
        - docker manifest annotate ${DOCKERHUB}:latest ${DOCKERHUB}:arm64 --os linux --arch arm64 --variant v8
        # Login to DockerHub
        - <<: *docker_login
        # Push all of the tags
        - docker manifest push ${DOCKERHUB}:latest
