language: bash
os: linux

services:
  - docker

env:
  global:
    - DOCKERHUB="thecaptain989/lidarr"

if: (NOT (type IN (pull_request)))

jobs:
  include:
    - stage: Build Images
      name: Build AMD64
      arch: amd64
      script:
        # Build variables
        - VERSION=$(git describe --tags --always)
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          --file Dockerfile
          --tag ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:amd64
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push the tag
        - docker push ${DOCKERHUB}:amd64
    - name: Build Arm64
      arch: arm64
      script:
        # Build variables
        - VERSION=$(git describe --tags --always)
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          --file Dockerfile.arm64
          --tag ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:arm64
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push the tag
        - docker push ${DOCKERHUB}:arm64
    - stage: Docker Hub create manifest
      env: DOCKER_CLI_EXPERIMENTAL=enabled
      script:
        - docker pull ${DOCKERHUB}:amd64
        - docker pull ${DOCKERHUB}:arm64
        - docker manifest create ${DOCKERHUB}:latest ${DOCKERHUB}:amd64 ${DOCKERHUB}:arm64
        - docker manifest annotate ${DOCKERHUB}:latest ${DOCKERHUB}:arm64 --os linux --arch arm64 --variant v8
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker manifest push ${DOCKERHUB}:latest
