---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 400            # Line length 80 is far too short
MD022:
  lines_below: 0              # Headings only need a blank line before
MD025: false                  # Allow multiple top level headings
MD026:
  punctuation: ".,;:!。，；:"    # List of not allowed
MD028: false                  # Allow block quotes to be separated by blank lines
MD029: false                  # Ordered list item prefix
MD032: false                  # Lists don't need blank lines
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading

#################
# Rules by tags #
#################